name: advanced_weather_app
description: "A professional weather app with charts and advanced UI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  geolocator: ^13.0.1
  http: ^1.2.2
  intl: ^0.19.0
  fl_chart: ^0.70.2  # Nueva dependencia para los gráficos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
